apiVersion: 1

datasources:
  - name: ProofVault Prometheus
    type: prometheus
    uid: proofvault-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
