spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/proofvault_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:proofvault}
    password: ${DB_PASSWORD:proofvault_local_password}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}

proofvault:
  auth:
    bootstrap:
      enabled: ${AUTH_BOOTSTRAP_ENABLED:true}
      redirect-uris: ${AUTH_FRONTEND_REDIRECT_URI:http://localhost:5173/oauth2/callback,http://localhost:3000/oauth2/callback}
      post-logout-redirect-uris: ${AUTH_FRONTEND_LOGOUT_REDIRECT_URI:http://localhost:5173,http://localhost:3000}
    signing:
      require-configured-key: ${AUTH_SIGNING_REQUIRE_CONFIGURED_KEY:false}
      private-key-pem: ${AUTH_SIGNING_PRIVATE_KEY_PEM:}
      public-key-pem: ${AUTH_SIGNING_PUBLIC_KEY_PEM:}
    wallet:
      domain: ${AUTH_WALLET_DOMAIN:localhost:5173}
      uri: ${AUTH_WALLET_URI:http://localhost:5173}

management:
  tracing:
    enabled: ${OTEL_TRACING_ENABLED:false}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
